version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 692454124440.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
      - docker build -t quest-api:latest .
      - docker tag quest-api:latest 692454124440.dkr.ecr.us-east-1.amazonaws.com/quest-api:latest
  post_build:
    commands:
      - docker push 692454124440.dkr.ecr.us-east-1.amazonaws.com/quest-api:latest
