version: 0.2

phases:
  pre_build:
    commands:
      - echo "ENVIRONMENT variable is set to staging"
      - echo "REPOSITORY_URI variable is set to 692454124440.dkr.ecr.us-east-1.amazonaws.com/staging-quest-api-v2"
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 692454124440.dkr.ecr.us-east-1.amazonaws.com/staging-quest-api-v2
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t quest-api:staging .
      - docker tag quest-api:staging 692454124440.dkr.ecr.us-east-1.amazonaws.com/staging-quest-api-v2:staging
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 692454124440.dkr.ecr.us-east-1.amazonaws.com/staging-quest-api-v2:staging
      - echo Writing image definitions file...
      - printf '[{"name":"quest-api","imageUri":"%s:%s"}]' 692454124440.dkr.ecr.us-east-1.amazonaws.com/staging-quest-api-v2 staging > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
