version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t quest-api:$ENVIRONMENT .
      - docker tag quest-api:staging $REPOSITORY_URI:staging
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$ENVIRONMENT
      - echo Writing image definitions file...
      - printf '[{"name":"quest-api","imageUri":"%s/quest-api:%s"}]' $REPOSITORY_URI $ENVIRONMENT > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
